# this file is concatonated onto Dockerfile for use in building a test image
RUN apt-get install -y firefox xvfb
RUN apt-get install -y haveged
RUN pip install -r requirements/test-requirements.txt
COPY . /app
RUN make test-config

CMD ["pytest"]
