#!/bin/bash
set -euo pipefail
set -x
Xvfb :1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
export DISPLAY=:1
haveged &
redis-server &
tail -F tests/log/firefox.log &
mkdir -p "/tmp/test-results/logs"
trap 'bash <(curl -s https://codecov.io/bash); cp -r tests/log /tmp/test-results/' EXIT ERR

export SCREENSHOTS_ENABLED=1
pytest \
  --junitxml=/tmp/test-results/junit.xml \
  --cov-report html:/tmp/test-results/cov_html \
  --cov-report xml:/tmp/test-results/cov.xml \
  --cov-report annotate:/tmp/test-results/cov_annotate \
  --cov=. \
  "$@"
